# generated by https://github.com/puzl-cloud/kubesdk
from .v1 import StorageVersionMigration, StorageVersionMigrationList, StorageVersionMigrationSpec, StorageVersionMigrationStatus




__all__ = ['StorageVersionMigration', 'StorageVersionMigrationList', 'StorageVersionMigrationSpec', 'StorageVersionMigrationStatus']

