# generated by https://github.com/puzl-cloud/kubesdk
#   filename:  apis__batch__v1_openapi.json

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import ClassVar, List, Set

from kube_models.const import *
from kube_models.loader import *
from kube_models.loader import Loadable
from kube_models.resource import *


@dataclass(slots=True, kw_only=True, frozen=True)
class TopologyConstraint(Loadable):
    key: str


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupAllDisruptionMode(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupBasicSchedulingPolicy(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupGangSchedulingPolicy(Loadable):
    minCount: int | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupResourceClaim(Loadable):
    name: str
    resourceClaimName: str | None = None
    resourceClaimTemplateName: str | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupSchedulingConstraints(Loadable):
    topology: List[TopologyConstraint] | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupSchedulingPolicy(Loadable):
    basic: WorkloadPodGroupBasicSchedulingPolicy | None = None
    gang: WorkloadPodGroupGangSchedulingPolicy | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupSingleDisruptionMode(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadPodGroupDisruptionMode(Loadable):
    all: WorkloadPodGroupAllDisruptionMode | None = None
    single: WorkloadPodGroupSingleDisruptionMode | None = None
