# generated by https://github.com/puzl-cloud/kubesdk
from .v1alpha2 import BasicSchedulingPolicy, GangSchedulingPolicy, PodGroup, PodGroupList, PodGroupResourceClaim, PodGroupResourceClaimStatus, PodGroupSchedulingConstraints, PodGroupSchedulingPolicy, PodGroupSpec, PodGroupStatus, PodGroupTemplate, PodGroupTemplateReference, TopologyConstraint, TypedLocalObjectReference, Workload, WorkloadList, WorkloadPodGroupTemplateReference, WorkloadSpec




__all__ = ['BasicSchedulingPolicy', 'GangSchedulingPolicy', 'PodGroup', 'PodGroupList', 'PodGroupResourceClaim', 'PodGroupResourceClaimStatus', 'PodGroupSchedulingConstraints', 'PodGroupSchedulingPolicy', 'PodGroupSpec', 'PodGroupStatus', 'PodGroupTemplate', 'PodGroupTemplateReference', 'TopologyConstraint', 'TypedLocalObjectReference', 'Workload', 'WorkloadList', 'WorkloadPodGroupTemplateReference', 'WorkloadSpec']

