# generated by https://github.com/puzl-cloud/kubesdk
#   filename:  apis__scheduling.k8s.io__v1beta1_openapi.json

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import ClassVar, List, Set

from kube_models.const import *
from kube_models.loader import *
from kube_models.loader import Loadable
from kube_models.resource import *

from ...apimachinery.pkg.apis.meta.v1 import Condition, ListMeta, ObjectMeta


@dataclass(slots=True, kw_only=True, frozen=True)
class AllCompositeDisruptionMode(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class AllDisruptionMode(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class BasicSchedulingPolicy(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class CompositeBasicSchedulingPolicy(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class CompositeGangSchedulingPolicy(Loadable):
    minGroupCount: int


@dataclass(slots=True, kw_only=True, frozen=True)
class CompositePodGroupSchedulingPolicy(Loadable):
    basic: CompositeBasicSchedulingPolicy | None = None
    gang: CompositeGangSchedulingPolicy | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class GangSchedulingPolicy(Loadable):
    minCount: int


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupResourceClaim(Loadable):
    name: str
    resourceClaimName: str | None = None
    resourceClaimTemplateName: str | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupResourceClaimStatus(Loadable):
    name: str
    resourceClaimName: str | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupSchedulingPolicy(Loadable):
    basic: BasicSchedulingPolicy | None = None
    gang: GangSchedulingPolicy | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class SingleCompositeDisruptionMode(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class SingleDisruptionMode(Loadable):
    pass


@dataclass(slots=True, kw_only=True, frozen=True)
class TopologyConstraint(Loadable):
    key: str


@dataclass(slots=True, kw_only=True, frozen=True)
class TypedLocalObjectReference(Loadable):
    kind: str
    name: str
    apiGroup: str | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadReference(Loadable):
    templateName: str
    workloadName: str


@dataclass(slots=True, kw_only=True, frozen=True)
class CompositeDisruptionMode(Loadable):
    all: AllCompositeDisruptionMode | None = None
    single: SingleCompositeDisruptionMode | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class CompositePodGroupSchedulingConstraints(Loadable):
    topology: List[TopologyConstraint] | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class DisruptionMode(Loadable):
    all: AllDisruptionMode | None = None
    single: SingleDisruptionMode | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupSchedulingConstraints(Loadable):
    topology: List[TopologyConstraint] | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupSpec(Loadable):
    schedulingPolicy: PodGroupSchedulingPolicy
    disruptionMode: DisruptionMode | None = field(
        default_factory=lambda: {'single': {}}
    )
    parentCompositePodGroupName: str | None = None
    preemptionPolicy: str | None = None
    priority: int | None = None
    priorityClassName: str | None = None
    resourceClaims: List[PodGroupResourceClaim] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge,retainKeys',
            'x-kubernetes-patch-merge-key': 'name',
        },
    )
    schedulingConstraints: PodGroupSchedulingConstraints | None = None
    workloadRef: WorkloadReference | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupTemplate(Loadable):
    name: str
    schedulingPolicy: PodGroupSchedulingPolicy
    disruptionMode: DisruptionMode | None = None
    preemptionPolicy: str | None = None
    priority: int | None = None
    priorityClassName: str | None = None
    resourceClaims: List[PodGroupResourceClaim] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge,retainKeys',
            'x-kubernetes-patch-merge-key': 'name',
        },
    )
    schedulingConstraints: PodGroupSchedulingConstraints | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class CompositePodGroupTemplate(Loadable):
    name: str
    schedulingPolicy: CompositePodGroupSchedulingPolicy
    compositePodGroupTemplates: List[CompositePodGroupTemplate] | None = None
    disruptionMode: CompositeDisruptionMode | None = None
    podGroupTemplates: List[PodGroupTemplate] | None = None
    preemptionPolicy: str | None = None
    priority: int | None = None
    priorityClassName: str | None = None
    schedulingConstraints: CompositePodGroupSchedulingConstraints | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupStatus(Loadable):
    conditions: List[Condition] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge',
            'x-kubernetes-patch-merge-key': 'type',
        },
    )
    resourceClaimStatuses: List[PodGroupResourceClaimStatus] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge,retainKeys',
            'x-kubernetes-patch-merge-key': 'name',
        },
    )


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadSpec(Loadable):
    compositePodGroupTemplates: List[CompositePodGroupTemplate] | None = None
    controllerRef: TypedLocalObjectReference | None = None
    podGroupTemplates: List[PodGroupTemplate] | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroup(K8sResource):
    spec: PodGroupSpec
    apiVersion: ClassVar[str] = 'scheduling.k8s.io/v1beta1'
    kind: ClassVar[str] = 'PodGroup'
    metadata: ObjectMeta = field(default_factory=ObjectMeta)
    status: PodGroupStatus | None = None
    plural_: ClassVar[str] = 'podgroups'
    is_namespaced_: ClassVar[bool] = True
    group_: ClassVar[Optional[str]] = 'scheduling.k8s.io'
    patch_strategies_: ClassVar[set[PatchRequestType]] = {
        'application/apply-patch+cbor',
        'application/apply-patch+yaml',
        'application/json-patch+json',
        'application/merge-patch+json',
        'application/strategic-merge-patch+json',
    }


@dataclass(slots=True, kw_only=True, frozen=True)
class PodGroupList(Loadable):
    items: List[PodGroup]
    apiVersion: str = 'scheduling.k8s.io/v1beta1'
    kind: str = 'PodGroupList'
    metadata: ListMeta = field(default_factory=ObjectMeta)


@dataclass(slots=True, kw_only=True, frozen=True)
class Workload(K8sResource):
    spec: WorkloadSpec
    apiVersion: ClassVar[str] = 'scheduling.k8s.io/v1beta1'
    kind: ClassVar[str] = 'Workload'
    metadata: ObjectMeta = field(default_factory=ObjectMeta)
    plural_: ClassVar[str] = 'workloads'
    is_namespaced_: ClassVar[bool] = True
    group_: ClassVar[Optional[str]] = 'scheduling.k8s.io'
    patch_strategies_: ClassVar[set[PatchRequestType]] = {
        'application/apply-patch+cbor',
        'application/apply-patch+yaml',
        'application/json-patch+json',
        'application/merge-patch+json',
        'application/strategic-merge-patch+json',
    }


@dataclass(slots=True, kw_only=True, frozen=True)
class WorkloadList(Loadable):
    items: List[Workload]
    apiVersion: str = 'scheduling.k8s.io/v1beta1'
    kind: str = 'WorkloadList'
    metadata: ListMeta = field(default_factory=ObjectMeta)
