# generated by https://github.com/puzl-cloud/kubesdk
from .v1alpha1 import Eviction, EvictionList, EvictionPodReference, EvictionRequest, EvictionRequestList, EvictionRequestPodReference, EvictionRequestSpec, EvictionRequestStatus, EvictionRequestTarget, EvictionSpec, EvictionStatus, EvictionTarget, Requester, ResponderStatus, TargetResponder




__all__ = ['Eviction', 'EvictionList', 'EvictionPodReference', 'EvictionRequest', 'EvictionRequestList', 'EvictionRequestPodReference', 'EvictionRequestSpec', 'EvictionRequestStatus', 'EvictionRequestTarget', 'EvictionSpec', 'EvictionStatus', 'EvictionTarget', 'Requester', 'ResponderStatus', 'TargetResponder']

