# generated by https://github.com/puzl-cloud/kubesdk
#   filename:  apis__lifecycle.k8s.io__v1alpha1_openapi.json

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import ClassVar, List, Set

from kube_models.const import *
from kube_models.loader import *
from kube_models.loader import Loadable
from kube_models.resource import *

from ...apimachinery.pkg.apis.meta.v1 import Condition, ListMeta, ObjectMeta, Time


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionPodReference(Loadable):
    name: str
    uid: str


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionRequestPodReference(Loadable):
    name: str
    uid: str


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionRequestTarget(Loadable):
    pod: EvictionRequestPodReference | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionTarget(Loadable):
    pod: EvictionPodReference | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class Requester(Loadable):
    intent: str
    name: str


@dataclass(slots=True, kw_only=True, frozen=True)
class TargetResponder(Loadable):
    name: str
    priority: int
    state: str


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionRequestSpec(Loadable):
    intent: str
    requester: str
    target: EvictionRequestTarget


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionSpec(Loadable):
    target: EvictionTarget


@dataclass(slots=True, kw_only=True, frozen=True)
class ResponderStatus(Loadable):
    name: str
    completionTime: Time | None = None
    expectedCompletionTime: Time | None = None
    heartbeatTime: Time | None = None
    message: str | None = None
    startTime: Time | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionRequestStatus(Loadable):
    conditions: List[Condition] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge',
            'x-kubernetes-patch-merge-key': 'type',
        },
    )
    observedGeneration: int | None = None


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionStatus(Loadable):
    conditions: List[Condition] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge',
            'x-kubernetes-patch-merge-key': 'type',
        },
    )
    observedGeneration: int | None = None
    requesters: List[Requester] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge',
            'x-kubernetes-patch-merge-key': 'name',
        },
    )
    responders: List[ResponderStatus] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge',
            'x-kubernetes-patch-merge-key': 'name',
        },
    )
    targetResponders: List[TargetResponder] = field(
        default_factory=list,
        metadata={
            'x-kubernetes-patch-strategy': 'merge',
            'x-kubernetes-patch-merge-key': 'name',
        },
    )


@dataclass(slots=True, kw_only=True, frozen=True)
class Eviction(K8sResource):
    spec: EvictionSpec
    apiVersion: ClassVar[str] = 'lifecycle.k8s.io/v1alpha1'
    kind: ClassVar[str] = 'Eviction'
    metadata: ObjectMeta = field(default_factory=ObjectMeta)
    status: EvictionStatus | None = None
    plural_: ClassVar[str] = 'evictions'
    is_namespaced_: ClassVar[bool] = True
    group_: ClassVar[Optional[str]] = 'lifecycle.k8s.io'
    patch_strategies_: ClassVar[set[PatchRequestType]] = {
        'application/apply-patch+cbor',
        'application/apply-patch+yaml',
        'application/json-patch+json',
        'application/merge-patch+json',
        'application/strategic-merge-patch+json',
    }


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionList(Loadable):
    items: List[Eviction]
    apiVersion: str = 'lifecycle.k8s.io/v1alpha1'
    kind: str = 'EvictionList'
    metadata: ListMeta = field(default_factory=ObjectMeta)


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionRequest(K8sResource):
    spec: EvictionRequestSpec
    apiVersion: ClassVar[str] = 'lifecycle.k8s.io/v1alpha1'
    kind: ClassVar[str] = 'EvictionRequest'
    metadata: ObjectMeta = field(default_factory=ObjectMeta)
    status: EvictionRequestStatus | None = None
    plural_: ClassVar[str] = 'evictionrequests'
    is_namespaced_: ClassVar[bool] = True
    group_: ClassVar[Optional[str]] = 'lifecycle.k8s.io'
    patch_strategies_: ClassVar[set[PatchRequestType]] = {
        'application/apply-patch+cbor',
        'application/apply-patch+yaml',
        'application/json-patch+json',
        'application/merge-patch+json',
        'application/strategic-merge-patch+json',
    }


@dataclass(slots=True, kw_only=True, frozen=True)
class EvictionRequestList(Loadable):
    items: List[EvictionRequest]
    apiVersion: str = 'lifecycle.k8s.io/v1alpha1'
    kind: str = 'EvictionRequestList'
    metadata: ListMeta = field(default_factory=ObjectMeta)
